package com.rliconnect.rli.connect.rules.pup;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String firstName;
	private java.lang.String lastName;
	private java.lang.Integer age;
	private java.lang.Double premium;

	public Customer() {
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Double getPremium() {
		return this.premium;
	}

	public void setPremium(java.lang.Double premium) {
		this.premium = premium;
	}

	public Customer(java.lang.String firstName, java.lang.String lastName,
			java.lang.Integer age, java.lang.Double premium) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.age = age;
		this.premium = premium;
	}

}